// Generated by gencpp from file dynamixel_sdk_examples/BulkGetItemResponse.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_SDK_EXAMPLES_MESSAGE_BULKGETITEMRESPONSE_H
#define DYNAMIXEL_SDK_EXAMPLES_MESSAGE_BULKGETITEMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamixel_sdk_examples
{
template <class ContainerAllocator>
struct BulkGetItemResponse_
{
  typedef BulkGetItemResponse_<ContainerAllocator> Type;

  BulkGetItemResponse_()
    : value1(0)
    , value2(0)  {
    }
  BulkGetItemResponse_(const ContainerAllocator& _alloc)
    : value1(0)
    , value2(0)  {
  (void)_alloc;
    }



   typedef int32_t _value1_type;
  _value1_type value1;

   typedef int32_t _value2_type;
  _value2_type value2;





  typedef boost::shared_ptr< ::dynamixel_sdk_examples::BulkGetItemResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_sdk_examples::BulkGetItemResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BulkGetItemResponse_

typedef ::dynamixel_sdk_examples::BulkGetItemResponse_<std::allocator<void> > BulkGetItemResponse;

typedef boost::shared_ptr< ::dynamixel_sdk_examples::BulkGetItemResponse > BulkGetItemResponsePtr;
typedef boost::shared_ptr< ::dynamixel_sdk_examples::BulkGetItemResponse const> BulkGetItemResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamixel_sdk_examples::BulkGetItemResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamixel_sdk_examples::BulkGetItemResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dynamixel_sdk_examples

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'dynamixel_sdk_examples': ['/home/gaurav/catkin_ws/src/DynamixelSDK/ros/dynamixel_sdk_examples/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_sdk_examples::BulkGetItemResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_sdk_examples::BulkGetItemResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_sdk_examples::BulkGetItemResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_sdk_examples::BulkGetItemResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_sdk_examples::BulkGetItemResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_sdk_examples::BulkGetItemResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_sdk_examples::BulkGetItemResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e5963c91be0598b7f68fed70b98f2326";
  }

  static const char* value(const ::dynamixel_sdk_examples::BulkGetItemResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe5963c91be0598b7ULL;
  static const uint64_t static_value2 = 0xf68fed70b98f2326ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_sdk_examples::BulkGetItemResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamixel_sdk_examples/BulkGetItemResponse";
  }

  static const char* value(const ::dynamixel_sdk_examples::BulkGetItemResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_sdk_examples::BulkGetItemResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 value1\n\
int32 value2\n\
\n\
";
  }

  static const char* value(const ::dynamixel_sdk_examples::BulkGetItemResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamixel_sdk_examples::BulkGetItemResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value1);
      stream.next(m.value2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BulkGetItemResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamixel_sdk_examples::BulkGetItemResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamixel_sdk_examples::BulkGetItemResponse_<ContainerAllocator>& v)
  {
    s << indent << "value1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value1);
    s << indent << "value2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIXEL_SDK_EXAMPLES_MESSAGE_BULKGETITEMRESPONSE_H
